name: build-deb

on:
  push:
  workflow_dispatch:

jobs:
  theos-build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          brew install ldid || true

      - name: 安装 Theos
        run: |
          export THEOS=$HOME/theos
          rm -rf $THEOS
          git clone --depth=1 https://github.com/theos/theos.git $THEOS
          cd $THEOS
          git submodule update --init --recursive
          echo "THEOS=$HOME/theos" >> "$GITHUB_ENV"

      - name: 补 iOS SDK
        run: |
          export THEOS=$HOME/theos
          rm -rf $THEOS/sdks
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks

      - name: 强制转换 control 换行符
        run: |
          sed -i '' 's/\r$//' control || true

      - name: 编译 rootless .deb
        run: |
          export THEOS=$HOME/theos
          export PATH="$(brew --prefix)/bin:$PATH"
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
          ls -la packages

      - uses: actions/upload-artifact@v4
        with:
          name: camhook-deb
          path: packages/*.deb
